### PR TITLE
NWIS parameter code option

### PR DESCRIPTION
**Pull request by jdhughes-usgs**
Added optional functionality to pass NWIS parameter code to get retrieve data types in addition to discharge (parameterCd='00060'). Updated autotests and added a test of NWIS parameter code use.

### CODE REVIEW

**Comment by mroberge** [comment]
Thanks! This is great!

**Comment by jdhughes-usgs** [comment]
Any chance that you will be doing a PyPi release in the next month? I am teaching a USGS python class at the end of the month and would like to use hydrofunctions as part of the class to work with NWIS streamflow, stage, etc. data.

**Comment by mroberge** [comment]
Sure! I'd be happy to do that. I haven't worked on hydrofunctions in a while, so I'm a little rusty on where everything is. Would you like to add yourself to the AUTHORS.rst? or I can do it.

**Comment by jdhughes-usgs** [comment]
I can add my name to AUTHORS.rst. Let me work with hydrofunctions for a couple more weeks to see if there is any additional functionality that might be nice to add.

**Pull request merged**
