### PR TITLE
pandas catchup?

### PR DESCRIPTION
**Pull request by jmccreight**
Apparently a very small change to keep up with pandas

### CODE REVIEW

**Comment by mroberge** [comment]
@jmccreight  Thank you for this commit! Could you please do a pull request into my Develop branch, please? That will run all of the tests automatically. In the meantime, I need to update the system I use to publish to PyPI.

**Comment by jmccreight** [comment]
I just changed the base of the PR to develop. But it did not trigger a new test.

**Comment by jmccreight** [comment]
I just changed the base of the PR to develop. But it did not trigger a new test.

**Comment by jmccreight** [comment]
I'm closing this and adding the edit to develop.

**Pull request closed without merging**
